#include <array>
#include <cstdint>
#include <iostream>
#include <vector>
#include <algorithm>
#include <queue>
using namespace std;
struct Part{array<int,4>o;int k;array<int,4>cls;vector<int>beliefs;};
vector<Part> gen_parts(){vector<Part>out;array<int,4>a{0,0,0,0};auto rec=[&](auto&&self,int i,int mx)->void{if(i==4){Part p;p.o=a;p.k=mx+1;p.cls.fill(0);for(int s=0;s<4;s++)p.cls[a[s]]|=1<<s;bool seen[16]{};for(int c=0;c<p.k;c++)for(int b=p.cls[c];b;b=(b-1)&p.cls[c])if(!seen[b]){seen[b]=1;p.beliefs.push_back(b);}sort(p.beliefs.begin(),p.beliefs.end());out.push_back(p);return;}for(int x=0;x<=mx+1;x++){a[i]=x;self(self,i+1,max(mx,x));}};rec(rec,1,0);return out;}
array<int,4> mt(int b){array<int,4>f{};for(int s=0;s<4;s++)f[s]=(b>>(2*s))&3;return f;}
int post(int B,const array<int,4>&f){int r=0;for(int s=0;s<4;s++)if(B>>s&1)r|=1<<f[s];return r;}
vector<int> succs(int B,const array<int,4>&f,const Part&p){int q=post(B,f);vector<int>r;for(int c=0;c<p.k;c++){int x=q&p.cls[c];if(x)r.push_back(x);}sort(r.begin(),r.end());r.erase(unique(r.begin(),r.end()),r.end());return r;}
bool belief_win(const array<int,4>&f0,const array<int,4>&f1,const Part&p,int target){bool W[16]{};W[1<<target]=true;bool change=true;while(change){change=false;for(int B:p.beliefs)if(!W[B])for(auto*fp:{&f0,&f1}){auto ss=succs(B,*fp,p);bool ok=!ss.empty();for(int x:ss)ok&=W[x];if(ok){W[B]=true;change=true;break;}}}for(int c=0;c<p.k;c++)if(!W[p.cls[c]])return false;return true;}
bool memless_win(const array<int,4>&f0,const array<int,4>&f1,const Part&p,int target){for(int pol=0;pol<(1<<p.k);pol++){bool all=true;for(int start=0;start<4&&all;start++){int s=start;bool seen[4]{};bool hit=false;for(int step=0;step<8;step++){if(s==target){hit=true;break;}if(seen[s])break;seen[s]=true;int act=(pol>>p.o[s])&1;s=(act?f1:f0)[s];}all&=hit;}if(all)return true;}return false;}
bool refines(const Part&f,const Part&c){for(int s=0;s<4;s++)for(int t=0;t<4;t++)if(f.o[s]==f.o[t]&&c.o[s]!=c.o[t])return false;return true;}
int shortest_word(const array<int,4>&f0,const array<int,4>&f1,int target){int goal=1<<target;array<int,16>d;d.fill(-1);queue<int>q;d[15]=0;q.push(15);while(!q.empty()){int B=q.front();q.pop();if(B==goal)return d[B];for(auto*fp:{&f0,&f1}){int N=post(B,*fp);if(d[N]<0){d[N]=d[B]+1;q.push(N);}}}return -1;}
bool ctrl_noobs(const array<int,4>&f0,const array<int,4>&f1,int target,int qn){int actionsets=1<<qn;int updtotal=1;for(int i=0;i<qn;i++)updtotal*=qn;for(int aa=0;aa<actionsets;aa++)for(int uu=0;uu<updtotal;uu++){int tmp=uu;vector<int>up(qn);for(int i=0;i<qn;i++){up[i]=tmp%qn;tmp/=qn;}bool all=true;for(int start=0;start<4&&all;start++){int s=start,m=0;bool seen[16]{};bool hit=false;for(int step=0;step<4*qn+2;step++){if(s==target){hit=true;break;}int key=4*m+s;if(seen[key])break;seen[key]=true;int act=(aa>>m)&1;s=(act?f1:f0)[s];m=up[m];}all&=hit;}if(all)return true;}return false;}
int main(){auto ps=gen_parts();if(ps.size()!=15)return 2;uint64_t models=0,cases=0,bw=0,mw=0,needmem=0,collapsed=0,mono=0;array<uint64_t,6>minB{},minM{};array<uint64_t,8>wordlen{};array<uint64_t,5>memdist{};for(int target=0;target<4;target++){vector<int>bs;for(int b=0;b<256;b++)if(((b>>(2*target))&3)==target)bs.push_back(b);for(int b0:bs)for(int b1:bs){models++;auto f0=mt(b0),f1=mt(b1);bool WB[15]{},WM[15]{};int mb=5,mm=5;for(int i=0;i<15;i++){cases++;WB[i]=belief_win(f0,f1,ps[i],target);WM[i]=memless_win(f0,f1,ps[i],target);bw+=WB[i];mw+=WM[i];needmem+=WB[i]&&!WM[i];if(WB[i])mb=min(mb,ps[i].k);if(WM[i])mm=min(mm,ps[i].k);if(ps[i].k==1&&WB[i]&&!WM[i])collapsed++;}minB[mb]++;minM[mm]++;for(int i=0;i<15;i++)for(int j=0;j<15;j++)if(refines(ps[i],ps[j])){if(WB[j]&&!WB[i])return 3;if(WM[j]&&!WM[i])return 4;mono++;}int L=shortest_word(f0,f1,target);if(L<0){wordlen[0]++;memdist[4]++;}else{if(L>=7)return 5;wordlen[L]++;int qmin=0;for(int q=1;q<=3;q++)if(ctrl_noobs(f0,f1,target,q)){qmin=q;break;}if(!qmin)return 6;memdist[qmin]++;}}}
cout<<"{\n  \"partitions\":15,\n  \"absorbing_target_model_pairs\":"<<models<<",\n  \"model_partition_cases\":"<<cases<<",\n  \"belief_winning_cases\":"<<bw<<",\n  \"memoryless_winning_cases\":"<<mw<<",\n  \"belief_win_memoryless_fail_cases\":"<<needmem<<",\n  \"collapsed_observation_memory_needed_models\":"<<collapsed<<",\n  \"refinement_implications_checked\":"<<mono<<",\n  \"min_observation_classes_belief\":[";for(int i=1;i<=5;i++){if(i>1)cout<<",";cout<<minB[i];}cout<<"],\n  \"min_observation_classes_memoryless\":[";for(int i=1;i<=5;i++){if(i>1)cout<<",";cout<<minM[i];}cout<<"],\n  \"shortest_open_loop_word_length\":{";bool first=true;for(int i=1;i<=6;i++)if(wordlen[i]){if(!first)cout<<",";first=false;cout<<"\""<<i<<"\":"<<wordlen[i];}cout<<",\"impossible\":"<<wordlen[0]<<"},\n  \"minimum_no_observation_controller_states\":{";cout<<"\"1\":"<<memdist[1]<<",\"2\":"<<memdist[2]<<",\"3\":"<<memdist[3]<<",\"impossible\":"<<memdist[4]<<"}\n}\n";}
