import { normalizeObserver } from './observer.mjs';

const DEG = Math.PI / 180;
const PLANE_INDEX = Object.freeze({xw:Object.freeze([0,3]),yw:Object.freeze([1,3]),zw:Object.freeze([2,3])});
export const IDENTITY4 = Object.freeze([1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1]);
export const LEGAL_MOVES = Object.freeze([
  Object.freeze({plane:'xw',degrees:1}),Object.freeze({plane:'xw',degrees:-1}),
  Object.freeze({plane:'yw',degrees:1}),Object.freeze({plane:'yw',degrees:-1}),
  Object.freeze({plane:'zw',degrees:1}),Object.freeze({plane:'zw',degrees:-1})
]);
const UNIT_ROUNDOFF = Number.EPSILON / 2;
const ROTATION_ROUNDING_OPS_BOUND = 12;

function assertMove(plane,degrees){if(!Object.hasOwn(PLANE_INDEX,plane))throw new RangeError(`unsupported plane: ${plane}`);if(!Number.isFinite(degrees)||Math.abs(degrees)!==1)throw new RangeError('degrees must be exactly +1 or -1');}
function assertMatrix4(m){if(!Array.isArray(m)||m.length!==16||m.some(v=>!Number.isFinite(v)))throw new TypeError('matrix must contain 16 finite values');}
function assertPoint4(p){if(!Array.isArray(p)||p.length!==4||p.some(v=>!Number.isFinite(v)))throw new TypeError('point must contain four finite coordinates');}

export function rotationMatrix4(plane,degrees){assertMove(plane,degrees);const [a,b]=PLANE_INDEX[plane],theta=degrees*DEG,c=Math.cos(theta),s=Math.sin(theta),m=[...IDENTITY4];m[4*a+a]=c;m[4*a+b]=-s;m[4*b+a]=s;m[4*b+b]=c;return Object.freeze(m);}
export function multiplyMatrix4(left,right){assertMatrix4(left);assertMatrix4(right);const out=new Array(16).fill(0);for(let i=0;i<4;i++)for(let j=0;j<4;j++){let sum=0;for(let k=0;k<4;k++)sum+=left[4*i+k]*right[4*k+j];out[4*i+j]=sum;}return Object.freeze(out);}
export function applyMatrix4(matrix,point){assertMatrix4(matrix);assertPoint4(point);const out=new Array(4).fill(0);for(let i=0;i<4;i++){let sum=0;for(let k=0;k<4;k++)sum+=matrix[4*i+k]*point[k];out[i]=sum;}return Object.freeze(out);}
export function composeActionMatrix(actions=[]){if(!Array.isArray(actions))throw new TypeError('actions must be an array');let matrix=IDENTITY4;for(const move of actions){if(!move||typeof move!=='object')throw new TypeError('move must be an object');assertMove(move.plane,move.degrees);matrix=multiplyMatrix4(rotationMatrix4(move.plane,move.degrees),matrix);}return matrix;}
function determinant4(a){return a[0]*(a[5]*(a[10]*a[15]-a[11]*a[14])-a[6]*(a[9]*a[15]-a[11]*a[13])+a[7]*(a[9]*a[14]-a[10]*a[13]))-a[1]*(a[4]*(a[10]*a[15]-a[11]*a[14])-a[6]*(a[8]*a[15]-a[11]*a[12])+a[7]*(a[8]*a[14]-a[10]*a[12]))+a[2]*(a[4]*(a[9]*a[15]-a[11]*a[13])-a[5]*(a[8]*a[15]-a[11]*a[12])+a[7]*(a[8]*a[13]-a[9]*a[12]))-a[3]*(a[4]*(a[9]*a[14]-a[10]*a[13])-a[5]*(a[8]*a[14]-a[10]*a[12])+a[6]*(a[8]*a[13]-a[9]*a[12]));}
export function matrixInvariantMetrics(matrix){assertMatrix4(matrix);let orthogonalityResidual=0,maxColumnNormResidual=0;for(let i=0;i<4;i++)for(let j=0;j<4;j++){let dot=0;for(let k=0;k<4;k++)dot+=matrix[4*k+i]*matrix[4*k+j];const target=i===j?1:0;const residual=Math.abs(dot-target);orthogonalityResidual=Math.max(orthogonalityResidual,residual);if(i===j)maxColumnNormResidual=Math.max(maxColumnNormResidual,residual);}const determinant=determinant4(matrix);return Object.freeze({orthogonalityResidual,maxColumnNormResidual,determinant,determinantResidual:Math.abs(determinant-1)});}
export function compareStatesQuantified(a,b,{absTolerance=0,relTolerance=0}={}){for(const [name,v] of [['absTolerance',absTolerance],['relTolerance',relTolerance]])if(!Number.isFinite(v)||v<0)throw new RangeError(`${name} must be finite and non-negative`);if(!a||!b||!Array.isArray(a.points)||!Array.isArray(b.points)||a.points.length!==b.points.length)throw new RangeError('states must have matching point counts');let maxAbsDelta=0,maxErrorRatio=0;const pointDeltas=[];for(let i=0;i<a.points.length;i++){const p=a.points[i],q=b.points[i];assertPoint4(p);assertPoint4(q);const delta=[];for(let j=0;j<4;j++){const d=p[j]-q[j],ad=Math.abs(d),tol=absTolerance+relTolerance*Math.max(Math.abs(p[j]),Math.abs(q[j]));const ratio=tol===0?(ad===0?0:Infinity):ad/tol;maxAbsDelta=Math.max(maxAbsDelta,ad);maxErrorRatio=Math.max(maxErrorRatio,ratio);delta.push(d);}pointDeltas.push(Object.freeze(delta));}return Object.freeze({equal:maxErrorRatio<=1,maxAbsDelta,maxErrorRatio,absTolerance,relTolerance,pointDeltas:Object.freeze(pointDeltas)});}
export function binary64AccumulationBudget(operationCount){if(!Number.isSafeInteger(operationCount)||operationCount<0)throw new RangeError('operationCount must be a non-negative safe integer');if(operationCount===0)return 0;const ku=operationCount*UNIT_ROUNDOFF;if(!Number.isFinite(ku)||ku>=1)throw new RangeError('operationCount makes the standard gamma bound undefined');return ku/(1-ku);}
function squaredNorm(p){let s=0;for(const v of p)s+=v*v;return s;}
function rotateLocal(point,move){const [a,b]=PLANE_INDEX[move.plane],theta=move.degrees*DEG,c=Math.cos(theta),s=Math.sin(theta),q=[...point];q[a]=point[a]*c-point[b]*s;q[b]=point[a]*s+point[b]*c;return q;}
function inverseActions(actions){return [...actions].reverse().map(move=>({plane:move.plane,degrees:-move.degrees}));}
function expectedSinglePlane(point,move,totalDegrees){const [a,b]=PLANE_INDEX[move.plane];let degrees=totalDegrees%360;if(degrees>180)degrees-=360;if(degrees<=-180)degrees+=360;const theta=degrees*DEG,c=Math.cos(theta),s=Math.sin(theta),q=[...point];q[a]=point[a]*c-point[b]*s;q[b]=point[a]*s+point[b]*c;return q;}
export function longHorizonRotationProbe({point,actions,repetitions,expectedAngleDegrees,inverseRoundTrip=false}){assertPoint4(point);if(!Array.isArray(actions)||actions.length===0)throw new TypeError('actions must be a non-empty array');for(const move of actions){if(!move||typeof move!=='object')throw new TypeError('move must be an object');assertMove(move.plane,move.degrees);}if(!Number.isSafeInteger(repetitions)||repetitions<1)throw new RangeError('repetitions must be a positive safe integer');let current=[...point];for(let i=0;i<repetitions;i++)for(const move of actions)current=rotateLocal(current,move);if(inverseRoundTrip){const inverse=inverseActions(actions);for(let i=0;i<repetitions;i++)for(const move of inverse)current=rotateLocal(current,move);}let expected;if(inverseRoundTrip)expected=[...point];else if(Number.isFinite(expectedAngleDegrees)&&actions.length===1)expected=expectedSinglePlane(point,actions[0],expectedAngleDegrees);else throw new TypeError('expectedAngleDegrees is required for a non-round-trip single-action probe');const maxAbsDelta=Math.max(...current.map((v,i)=>Math.abs(v-expected[i])));const normResidual=Math.abs(squaredNorm(current)-squaredNorm(expected));const moveCount=actions.length*repetitions*(inverseRoundTrip?2:1);const roundingOperationBudget=moveCount*ROTATION_ROUNDING_OPS_BOUND;const errorBudget=binary64AccumulationBudget(roundingOperationBudget);return Object.freeze({finalPoint:Object.freeze(current),expectedPoint:Object.freeze(expected),moveCount,roundingOperationBudget,errorBudget,maxAbsDelta,normResidual});}
export function exhaustiveRotationSweep(maxDepth=8){if(!Number.isSafeInteger(maxDepth)||maxDepth<0)throw new RangeError('maxDepth must be a non-negative safe integer');const rotations=LEGAL_MOVES.map(move=>rotationMatrix4(move.plane,move.degrees));let pathCount=0,maxOrthogonalityResidual=0,maxDeterminantResidual=0,maxColumnNormResidual=0;function visit(matrix,depth){pathCount++;const metrics=matrixInvariantMetrics(matrix);maxOrthogonalityResidual=Math.max(maxOrthogonalityResidual,metrics.orthogonalityResidual);maxDeterminantResidual=Math.max(maxDeterminantResidual,metrics.determinantResidual);maxColumnNormResidual=Math.max(maxColumnNormResidual,metrics.maxColumnNormResidual);if(depth===maxDepth)return;for(const rotation of rotations)visit(multiplyMatrix4(rotation,matrix),depth+1);}visit(IDENTITY4,0);return Object.freeze({maxDepth,pathCount,maxOrthogonalityResidual,maxDeterminantResidual,maxColumnNormResidual});}
export function observerConditionReport(point,observer={}){assertPoint4(point);const o=normalizeObserver(observer);const w=point[3],boundedW=Math.max(-0.9,w),denominator=1+o.wPerspective*boundedW;if(!(denominator>0.1))throw new RangeError('valid observer contract must keep denominator above 0.1');const clamped=w<-0.9,atClampBoundary=w===-0.9,scale=1/denominator;const localScaleSensitivityToW=clamped?0:o.wPerspective/(denominator*denominator);return Object.freeze({w,boundedW,clamped,atClampBoundary,denominator,scale,localScaleSensitivityToW,informationLoss:clamped,contractDenominatorFloorExclusive:0.1});}
